### ISSUE TITLE
Thank you for doing this!

### ISSUE THREAD

**Issue by mrnugget** [appleby/Lisp-In-Small-Pieces#1]
This is not a bug report. I just wanted to thank you for creating this repository!

I was close to putting LiSP back on the shelf again after I realized how much work it would be to update the code to make it work with a modern Scheme implementation. And, to be honest, I did that a few months back: I was so disheartened by the Makefile and the error messages given to me by Guile and Racket, that I put the book back on the shelf.

So, thank you! Your work here is gold, the treasure chest that doubles the value of LiSP for me!

**Comment by mrnugget** [comment]
(Oh, and feel free to close this once you received the message :))

**Comment by appleby** [comment]
Thanks for the kind words. I'm glad that someone else finds it useful :). I should probably update the docker and vm images soon, so thanks for reminding me.
